language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
# script: python tests/test_all_of_the_units.py
install: "pip install -r requirements.txt"
branches:
  only:
    - master
